#Minecraft server properties
#Fri Aug 14 23:06:17 BRT 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=hard
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:default
log-ips=true
max-chained-neighbor-updates=1000000
max-players=10
max-tick-time=180000
max-world-size=29999984
motd=aATM Lite 7| §fServidor Leve e Divertido!
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https\://github.com/Xaxadox/atm-lite-resourcepack/releases/download/v1.0.0/ATM_Lite_Pack.zip
resource-pack-id=
resource-pack-prompt=Aceite o visual melhorado do servidor ATM Lite!
resource-pack-sha1=d17d1738224ed2fd47fe13e77167a516e44f15a4
server-ip=
server-port=25565
simulation-distance=8
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=16
white-list=false
